### ISSUE TITLE
Indexer iota_getTransactionBlock fails with `Type Parameter 0 out of bounds (0)`

### ISSUE THREAD

**Issue by Thoralf-M** [iotaledger/iota#5789]
## Bug description

Requesting an invalid transaction with `"showInput": true` fails with `Type Parameter 0 out of bounds (0)`

## Version

- Version: 0.10.0-alpha

## Steps To reproduce the bug

```zsh
curl https://indexer.devnet.iota.cafe \
--header 'content-type: application/json' \
--data '{
    "jsonrpc": "2.0",
    "id": 1,
    "method": "iota_getTransactionBlock",
    "params": {
        "digest": "AcQ1Zz6ancTJGYuoMZV8DhHyGdbCGi6ajNsAmTUUZEJP",
        "options": { 
            "showInput": true
        }
    }
}' | jq .
```

## Expected behaviour

Should return the transaction data

## Actual behaviour

```JSON
{
  "jsonrpc": "2.0",
  "id": 1,
  "error": {
    "code": -32603,
    "message": "Type Parameter 0 out of bounds (0)"
  }
}
```

Note: it works with the node, the result is this:
```JSON
{
  "jsonrpc": "2.0",
  "id": 1,
  "result": {
    "digest": "AcQ1Zz6ancTJGYuoMZV8DhHyGdbCGi6ajNsAmTUUZEJP",
    "transaction": {
      "data": {
        "messageVersion": "v1",
        "transaction": {
          "kind": "ProgrammableTransaction",
          "inputs": [
            {
              "type": "pure",
              "valueType": null,
              "value": [
                104,
                183,
                41,
                107,
                221,
                103,
                170,
                31,
                100,
                189,
                179,
                159,
                223,
                197,
                136,
                29,
                50,
                5,
                221,
                109,
                190,
                157,
                148,
                103,
                169,
                184,
                76,
                52,
                242,
                111,
                246,
                49
              ]
            },
            {
              "type": "pure",
              "valueType": null,
              "value": [
                3,
                127,
                20,
                209,
                228,
                152,
                22,
                216,
                226,
                130,
                174,
                206,
                178,
                78,
                60,
                232,
                51,
                192,
                147,
                255,
                217,
                112,
                173,
                202,
                245,
                224,
                195,
                148,
                229,
                62,
                226,
                44,
                17,
                184,
                40,
                142,
                224,
                40,
                95,
                65,
                97,
                78,
                101,
                202,
                4,
                232,
                110,
                154,
                75,
                178,
                198,
                183,
                143,
                181,
                82,
                123,
                194,
                45,
                129,
                26,
                49,
                165,
                109,
                251,
                47,
                195,
                65,
                75,
                136,
                19,
                144,
                188,
                136,
                241,
                208,
                82,
                85,
                187,
                205,
                2,
                157,
                210,
                219,
                47,
                2,
                45,
                234,
                58,
                181,
                16,
                236,
                248,
                228,
                135,
                135,
                236,
                24
              ]
            }
          ],
          "transactions": [
            {
              "MoveCall": {
                "package": "0x0000000000000000000000000000000000000000000000000000000000000002",
                "module": "pay",
                "function": "join_vec",
                "arguments": [
                  {
                    "Input": 0
                  },
                  {
                    "Input": 1
                  }
                ]
              }
            }
          ]
        },
        "sender": "0xb62979320398473f15a7dbff45f3663ef36d8d5cdbea60c171f80c48d9ba32d1",
        "gasData": {
          "payment": [
            {
              "objectId": "0x68b7296bdd67aa1f64bdb39fdfc5881d3205dd6dbe9d9467a9b84c34f26ff631",
              "version": 4793,
              "digest": "71LpSYN1Aw8zGR7voESKWNM5nF5QprnK6ppzeqbGsDtb"
            }
          ],
          "owner": "0xb62979320398473f15a7dbff45f3663ef36d8d5cdbea60c171f80c48d9ba32d1",
          "price": "1000",
          "budget": "5000000"
        }
      },
      "txSignatures": [
        "ALNaN/cjRnghbN3XUYFK5416pOp4Wn8lb4iaaDnomjShADcYv2nYvE8Rsg8noccjwdwCC2CuK8ST00wL4yHnoAuQuV98vDgDw7Hh5ohTceKh005xLbFL6peQLebLNfxv8A=="
      ]
    },
    "timestampMs": "1741193754966",
    "checkpoint": "43317730"
  }
}
```

**Comment by kodemartin** [comment]
This might already have been solved by https://github.com/iotaledger/iota/pull/6976

**Comment by samuel-rufi** [comment]
Hi @kodemartin, seems like #6976 does not solve it. The failing TX can be reproduced by following Indexer RPC test: 

```rust
#[test]
fn reproduce_failing_tx_type_out_of_bounds() -> Result<(), anyhow::Error> {
    let ApiTestSetup {
        runtime,
        store,
        cluster,
        client,
    } = ApiTestSetup::get_or_init();

    runtime.block_on(async move {
        let (address, keypair): (_, AccountKeyPair) = get_key_pair();

        // fund and wait for gas object
        let gas = cluster
            .fund_address_and_return_gas(
                cluster.get_reference_gas_price().await,
                Some(500_000_000_000),
                address,
            )
            .await;
        indexer_wait_for_object(client, gas.0, gas.1).await;

        // build the failing PT: join_vec with zero type args
        let pt = {
            let mut builder = ProgrammableTransactionBuilder::new();

            let arg0 = builder
                .pure(vec![
                    104, 183, 41, 107, 221, 103, 170, 31, 100, 189, 179, 159, 223, 197, 136, 29,
                    50, 5, 221, 109, 190, 157, 148, 103, 169, 184, 76, 52, 242, 111, 246, 49,
                ])
                .expect("valid pure");

            let arg1 = builder
                .pure(vec![
                    3, 127, 20, 209, 228, 152, 22, 216, 226, 130, 174, 206, 178, 78, 60, 232, 51,
                    192, 147, 255, 217, 112, 173, 202, 245, 224, 195, 148, 229, 62, 226, 44, 17,
                    184, 40, 142, 224, 40, 95, 65, 97, 78, 101, 202, 4, 232, 110, 154, 75, 178,
                    198, 183, 143, 181, 82, 123, 194, 45, 129, 26, 49, 165, 109, 251, 47, 195, 65,
                    75, 136, 19, 144, 188, 136, 241, 208, 82, 85, 187, 205, 2, 157, 210, 219, 47,
                    2, 45, 234, 58, 181, 16, 236, 248, 228, 135, 135, 236, 24,
                ])
                .expect("valid pure");

            // **no** type arguments here!
            builder.programmable_move_call(
                ObjectID::from_str(
                    "0000000000000000000000000000000000000000000000000000000000000002",
                )?,
                Identifier::from_str("pay")?,
                Identifier::from_str("join_vec")?,
                Vec::new(),       // <-- empty list of TypeTag
                vec![arg0, arg1],
            );

            builder.finish()
        };

        let tx_data = TestTransactionBuilder::new(address, gas, 1000)
            .programmable(pt)
            .build();
        let signed = to_sender_signed_transaction(tx_data, &keypair);

        let _ = cluster
            .wallet
            .execute_transaction_may_fail(signed.clone())
                                              .await;

        let digest = signed.digest().clone();
        indexer_wait_for_transaction(digest.clone(), store, client).await;

        // sleep so that the test cluster can be fetched using curl
        println!("transaction to fetch: {}", digest);
        tokio::time::sleep(std::time::Duration::from_secs(300)).await;

        Ok(())
    })
}
```

You can query the error then using (you might need to adjust the port):

```sh
curl http://localhost:9124 \
--header 'content-type: application/json' \
--data '{
    "jsonrpc": "2.0",
    "id": 1,
    "method": "iota_getTransactionBlock",
    "params": {
        "digest": "<TX_DIGEST>",
        "options": {
            "showInput": true, "showEffects": true
        }
    }
}' | jq .
```

---

The key issue here is that `Resolver::pure_input_layouts()` fails at the [open_sig.instantiate(..)?](https://github.com/iotaledger/iota/blob/develop/crates/iota-package-resolver/src/lib.rs#L522) if no type arguments are provided, as in the transaction posted above by @Thoralf-M.

Maybe one solution to solve the issue for the Indexer RPC requests would be to adjust it on a higher level i.e. `iota-json-rpc-types`. So basically we could try to adjust the `IotaProgrammableTransactionBlock::try_from_with_package_resolver()` as follows:

```diff
IotaProgrammableTransactionBlock:

 async fn try_from_with_package_resolver(
        value: ProgrammableTransaction,
        package_resolver: Arc<Resolver<impl PackageStore>>,
    ) -> Result<Self, anyhow::Error> {
-         let input_types = package_resolver.pure_input_layouts(&value).await?;
+        // If the pure input layouts cannot be built, we will use `None` for the input types.
+        let input_types = match package_resolver.pure_input_layouts(&value).await {
+            Ok(pure_input_layouts) => pure_input_layouts,
+            Err(e) => {
+                tracing::warn!("pure_input_layouts failed: {:?}", e);
+                vec![None; value.inputs.len()]
+            }
+        };

        let ProgrammableTransaction { inputs, commands } = value;
        Ok(IotaProgrammableTransactionBlock {
            inputs: inputs
                .into_iter()
                .zip(input_types)
                .map(|(arg, layout)| IotaCallArg::try_from(arg, layout.as_ref()))
                .collect::<Result<_, _>>()?,
            commands: commands.into_iter().map(IotaCommand::from).collect(),
        })
    }
```

So if the pure input layouts cannot be built, we simply initialize them with  `None`. The loss of error information should be fine here, since we want to return failed transactions. Does that sound reasonable?

**Comment by samuel-rufi** [comment]
As @Thoralf-M mentioned, the node was able to return the transaction while the Indexer was not.
The fix I introduced in [#7346](https://github.com/iotaledger/iota/pull/7346) matches the response from the node before applying it.

As discussed yesterday, maybe we can revert https://github.com/iotaledger/iota/pull/6976 as part of this PR as this PR might fix the other issue as well. Looking into that.

**Comment by kodemartin** [comment]
@samuel-rufi #7346 is fine since it matches how the node handles this case.

As discussed, I disagree with reverting #6976 as it is an improvement over the previous implementation providing data that was previously missed by the error returned. #7346 does not compensate for this data as it returns `None` for all errors.

**Comment by samuel-rufi** [comment]
Thanks for further clarifying @kodemartin the https://github.com/iotaledger/iota/pull/6976 case. So since these two PRs are fixing a different behavior and https://github.com/iotaledger/iota/pull/7346 matches the node response, no further actions are needed here. Changing the issue status.
